### ISSUE TITLE
Scraper list empty

### ISSUE THREAD

**Issue by goodjaerb** [remeh/mehstation-config#1]
I created a platform and wanted to use the scraper. The list to choose a console to scrape for is empty. I have mehtadata downloaded and copied next to mehstation-config. I can run mehtadata -show-platforms and it shows the list in the terminal, so the command is working. I'm on Ubuntu. Probably something i did but i followed the instructions ;)

**Comment by remeh** [comment]
Hello,

Do you launch `mehstation-config` directly from its build dir ? Meaning with the command-line, in the same directory where there is `mehtadata` ?
E.g.:
```
go build (in mehtadata)
cp mehtadata path/to/mehstation-config
cd path/to/mehstation-config/
./mehstation-config
```
I have some plan to ease this process.

**Comment by goodjaerb** [comment]
Yes. I have a screenshot.
![screenshot_20161212-132512](https://cloud.githubusercontent.com/assets/23344536/21111756/0a803c60-c071-11e6-8af0-9017f7a8ad17.png)

**Comment by remeh** [comment]
Thanks for the screenshot. There is indeed a problem, mehstation-config looks for the mehtadata binary from the current working dir (this is why you must do `./mehstation-config` from the mehstation-config path and not for example by starting the binary from a file manager)

I can't reproduce here but I'm currently investigating for a fix (it'll open a dialog to find mehtadata when it can't be found automatically).

**Comment by remeh** [comment]
What is weird is that it should open an error popup if mehtadata can't be found. So in your case it should have found it, but didn't succeed to use it.

**Comment by goodjaerb** [comment]
It's not explicitly shown but i ran ./mehstation-config from that directory. Never showed an error.

**Comment by goodjaerb** [comment]
Just to check that the error window is working, I changed dirs and ran mehstation-config and when I select scrape it showed the error pop-up. So as you said, when I run it from ./mehstation-config, it must see it but doesn't use it somehow. 

I appreciate you looking into this. I was hoping to test the scraping capabilities compared to emulationstation.

**Comment by remeh** [comment]
I've found the problem and it's a really stupid mistake from my side :) Currently trying to fix this in order to push the modification for you to use it this evening.

**Comment by remeh** [comment]
Last commits I've just pushed should fix `mehstation-config`. You must pull the changes and recompile mehstation-config. (in mehstation-config: `git pull && make -j2`)
I hope the scraping will be good, I've planned to improve it these holidays.

**Comment by goodjaerb** [comment]
Looks good! I'm currently scraping. Thanks!
